//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSZV_M_Stuff
    {
        public int Id { get; set; }
        public int SZV_M_Id { get; set; }
        public int WorkerId { get; set; }
    
        public virtual FormsSZV_M FormsSZV_M { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
