//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSZV_TD
    {
        public int Id { get; set; }
        public Nullable<int> InsurerID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<bool> Annuled { get; set; }
        public Nullable<System.DateTime> AnnulDate { get; set; }
        public Nullable<System.DateTime> DateFilling { get; set; }
    }
}
