//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSZV_TD_Stuff
    {
        public int Id { get; set; }
        public Nullable<int> SZV_TD_Id { get; set; }
        public Nullable<int> WorkerId { get; set; }
    
        public virtual FormsSZV_TD FormsSZV_TD { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
