//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insurer()
        {
            this.FormsSZV_TD = new HashSet<FormsSZV_TD>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameShort { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<long> INN { get; set; }
        public Nullable<long> RegNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_TD> FormsSZV_TD { get; set; }
    }
}
