//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<long> InsuranceNumber { get; set; }
        public Nullable<long> INN { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Profession { get; set; }
    
        public virtual Profession Profession1 { get; set; }
        public virtual Sex Sex1 { get; set; }
    }
}
